# Generated by Django 4.1.1 on 2022-09-22 06:21

import cr.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoProds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=127)),
                ('pais_producto', models.CharField(max_length=127)),
                ('tipo_producto', models.CharField(max_length=127)),
                ('precio_unidad', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='VentaProds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.IntegerField()),
                ('numero_semana', cr.models.DateWeekTruncated()),
                ('nombre_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.catalogoprods')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='IngresoProds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ingresada', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('nombre_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr.catalogoprods')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
    ]
