# Generated by Django 4.1.1 on 2022-09-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresoprods',
            old_name='nombre_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='ventaprods',
            old_name='nombre_producto',
            new_name='producto',
        ),
        migrations.AlterField(
            model_name='catalogoprods',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ventaprods',
            name='numero_semana',
            field=models.CharField(max_length=20),
        ),
    ]
